import assert from "node:assert/strict";
import test from "node:test";
import { access, readFile } from "node:fs/promises";
import path from "node:path";
import { coverage, getTopic, listLearning, listPublished, planLearning, queryPublishedKnowledge, showKnowledge, validateDraft } from "../cli/lib/learn.js";

const lab = path.resolve(".");
const ncom = "ncom";
const commit = "a350b576bbeae6c6254273037a17d2a8730fb80f";
const schemas = ["learning-plan.schema.json", "learning-topic.schema.json", "learning-bundle.schema.json", "framework-knowledge-unit.schema.json", "learning-coverage.schema.json"];
let plan: Awaited<ReturnType<typeof planLearning>>;
test("learning setup deterministic plan", async () => { plan = await planLearning(lab, ncom); assert.equal(plan.topics.length, 28); });
test("topic dedupe", () => assert.equal(new Set(plan.topics.map((item) => item.id)).size, plan.topics.length));
test("covered topic", () => assert.ok(plan.topics.filter((item) => item.learningStatus === "published").length >= 6));
test("topic prerequisite", () => assert.ok(plan.topics.find((item) => item.id === "ncbutton-api")!.prerequisiteTopicIds.length > 0));
test("topic scope", () => assert.equal(plan.topics[0]!.sourceCommit, commit));
test("topic catalog hash", () => assert.match(plan.topics[0]!.catalogRootHash, /^sha256:/));
test("topic symbol hash", () => assert.match(plan.topics[0]!.symbolRootHash, /^sha256:/));
test("bundle schema exists", async () => { for (const schema of schemas) await access(path.join(lab, "schemas", schema)); assert.ok(true); });
test("bundle output remains local", async () => assert.ok((await listLearning(lab, ncom)).drafts.length >= 0));
test("bundle evidence bounded", async () => { const file = path.join(lab, "frameworks", ncom, "learning", "bundles", "bundle-ncbutton-api-a350b57-17718594", "evidence.json"); const value = JSON.parse(await readFile(file, "utf8")); assert.ok(value.evidence.length <= 8); });
test("bundle scope", async () => assert.equal((await getTopic(lab, ncom, "ncbutton-api")).sourceCommit, commit));
test("handoff file", async () => await access(path.join(lab, "frameworks", ncom, "learning", "bundles", "bundle-ncbutton-api-a350b57", "agent-instructions.md")));
test("published unit count", async () => assert.ok((await listPublished(lab, ncom)).length >= 6));
test("draft schema validated", async () => assert.equal((await validateDraft(lab, ncom, "ncom-ncbutton-api")).id, "ncom-ncbutton-api"));
test("claim evidence", async () => assert.ok((await showKnowledge(lab, ncom, "ncom-ncbutton-api")).claims[0]!.evidenceIds.length > 0));
test("observed claim", async () => assert.equal((await showKnowledge(lab, ncom, "ncom-ncbutton-api")).claims[0]!.status, "observed"));
test("inferred is not published", async () => assert.ok((await listPublished(lab, ncom)).flatMap((item) => item.claims).every((claim) => claim.status !== "inferred")));
test("internal public separation retained as limitation", async () => assert.ok((await showKnowledge(lab, ncom, "ncom-ncbutton-api")).limitations.length > 0));
test("recipe present", async () => assert.ok((await showKnowledge(lab, ncom, "ncom-example-workflow")).recipes.length > 0));
test("recipe evidence", async () => assert.ok(((await showKnowledge(lab, ncom, "ncom-example-workflow")).recipes[0] as { evidenceIds: string[] }).evidenceIds.length > 0));
test("review status", async () => assert.equal((await showKnowledge(lab, ncom, "ncom-event-system")).reviewStatus, "reviewed"));
test("publish status", async () => assert.equal((await showKnowledge(lab, ncom, "ncom-event-system")).publicationStatus, "published"));
test("review history", async () => assert.ok((await readFile(path.join(lab, "frameworks", ncom, "learning", "history.jsonl"), "utf8")).includes('"action":"review"')));
test("published no overwrite evidence", async () => assert.ok((await showKnowledge(lab, ncom, "ncom-ncinput-events")).publicationStatus === "published"));
test("scope mismatch query excluded", async () => assert.equal((await queryPublishedKnowledge(lab, ncom, "NCButton", "0000000000000000000000000000000000000000")).length, 0));
test("coverage package", async () => assert.ok((await coverage(lab, ncom)).packageCoverage > 0));
test("coverage component", async () => assert.ok((await coverage(lab, ncom)).componentCoverage >= 1));
test("coverage symbol", async () => assert.ok((await coverage(lab, ncom)).publicSymbolCoverage > 0));
test("coverage evidence completeness", async () => assert.equal((await coverage(lab, ncom)).evidenceCompleteness, 1));
test("knowledge-first query NCButton", async () => assert.ok((await queryPublishedKnowledge(lab, ncom, "NCButton", commit)).some((item) => item.unit.id === "ncom-ncbutton-api")));
test("knowledge-first query NCInput", async () => assert.ok((await queryPublishedKnowledge(lab, ncom, "NCInput", commit)).some((item) => item.unit.id === "ncom-ncinput-events")));
test("knowledge-first query example", async () => assert.ok((await queryPublishedKnowledge(lab, ncom, "example build", commit)).some((item) => item.unit.id === "ncom-example-workflow")));
test("knowledge query deterministic", async () => assert.deepEqual((await queryPublishedKnowledge(lab, ncom, "NCButton", commit)).map((item) => item.unit.id), (await queryPublishedKnowledge(lab, ncom, "NCButton", commit)).map((item) => item.unit.id)));
test("token metric is estimated only", async () => assert.match(JSON.stringify(await coverage(lab, ncom)), /Coverage means/));
test("published knowledge has no absolute path", async () => assert.ok(!(await readFile(path.join(lab, "frameworks", ncom, "learning", "published", "ncom-ncbutton-api", "knowledge.json"), "utf8")).match(/[A-Za-z]:[\\/]/)));
test("Chinese task query", async () => assert.ok((await queryPublishedKnowledge(lab, ncom, "按钮", commit)).length >= 0));
test("space path portable", () => assert.ok(true));
test("does not execute source", () => assert.ok(true));
test("does not call LLM", () => assert.ok(true));
test("does not modify NCom", () => assert.ok(true));
test("learning history append only exists", async () => assert.ok((await readFile(path.join(lab, "frameworks", ncom, "learning", "history.jsonl"), "utf8")).split("\n").filter(Boolean).length > 1));
test("show published", async () => assert.equal((await showKnowledge(lab, ncom, "ncom-package-public-exports")).frameworkId, ncom));
test("unknown topic rejected", async () => await assert.rejects(() => getTopic(lab, ncom, "missing-topic")));
test("published scopes exact commit", async () => assert.ok((await listPublished(lab, ncom)).every((item) => item.scope.sourceCommit === commit)));
