import { createHash } from "node:crypto";
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { diffCatalog } from "./catalog.js";
import { diffSymbols } from "./symbols.js";
import { listPublished } from "./learn.js";
import { validateWithSchema } from "./schema.js";

const sha = (v: string | Buffer) => `sha256:${createHash("sha256").update(v).digest("hex")}`;
const now = () => new Date().toISOString();
const vroot = (lab: string, id: string, ...parts: string[]) => path.join(lab, "frameworks", id, "versions", ...parts);
const lroot = (lab: string, id: string, ...parts: string[]) => path.join(lab, "frameworks", id, "learning", ...parts);
async function json<T>(file: string): Promise<T> { return JSON.parse(await readFile(file, "utf8")) as T; }
async function writeJson(file: string, value: unknown) { await mkdir(path.dirname(file), { recursive: true }); await writeFile(file, `${JSON.stringify(value, null, 2)}\n`, "utf8"); }

export interface FrameworkVersion { schemaVersion: string; versionId: string; frameworkId: string; repositoryUrl: string | null; sourceCommit: string; sourceTag: string | null; branch: string | null; catalogSnapshotId: string; catalogRootHash: string; symbolSnapshotId: string; symbolRootHash: string; knowledgeIndexSha256: string | null; createdAt: string; sourceClean: boolean; previousVersionId: string | null; scannerVersions: Record<string, string | null>; warnings: string[]; }
async function versions(lab: string, frameworkId: string) { const folder = vroot(lab, frameworkId, "versions"); try { return await Promise.all((await readdir(folder)).sort().map((id) => json<FrameworkVersion>(path.join(folder, id, "version.json")))); } catch { return []; } }
async function snapshot(lab: string, frameworkId: string, catalogId: string, symbolId: string) {
  const base = path.join(lab, "frameworks", frameworkId); const [catalog, symbols] = await Promise.all([
    json<{ sourceCommit: string; rootHash: string; dirty: boolean }>(path.join(base, "catalog", "snapshots", catalogId, "snapshot.json")),
    json<{ sourceCommit: string; rootHash: string }>(path.join(base, "symbols", "snapshots", symbolId, "analysis.json")),
  ]);
  if (catalog.sourceCommit !== symbols.sourceCommit) throw new Error("Catalog 与 Symbol Snapshot commit 不一致。");
  return { catalog, symbols };
}
export async function createVersion(lab: string, frameworkId: string, options: { catalogSnapshotId?: string; symbolSnapshotId?: string; versionId?: string; sourceTag?: string | null; branch?: string | null }) {
  const base = path.join(lab, "frameworks", frameworkId); const [catalogCurrent, symbolCurrent] = await Promise.all([json<{ snapshotId: string }>(path.join(base, "catalog", "current.json")), json<{ snapshotId: string }>(path.join(base, "symbols", "current.json"))]);
  const catalogSnapshotId = options.catalogSnapshotId ?? catalogCurrent.snapshotId, symbolSnapshotId = options.symbolSnapshotId ?? symbolCurrent.snapshotId; const data = await snapshot(lab, frameworkId, catalogSnapshotId, symbolSnapshotId);
  const sourceCommit = data.catalog.sourceCommit, versionId = options.versionId ?? `${(options.sourceTag ?? sourceCommit).replace(/[^A-Za-z0-9._-]/gu, "-")}-${sourceCommit.slice(0, 7)}`;
  const all = await versions(lab, frameworkId); if (all.some((item) => item.versionId === versionId)) throw new Error(`Version 已存在：${versionId}`);
  const knowledgeIndex = await readFile(path.join(base, "knowledge", "index.json"), "utf8").catch(() => null);
  const version: FrameworkVersion = { schemaVersion: "1.0.0", versionId, frameworkId, repositoryUrl: null, sourceCommit, sourceTag: options.sourceTag ?? null, branch: options.branch ?? null, catalogSnapshotId, catalogRootHash: data.catalog.rootHash, symbolSnapshotId, symbolRootHash: data.symbols.rootHash, knowledgeIndexSha256: knowledgeIndex ? sha(knowledgeIndex) : null, createdAt: now(), sourceClean: !data.catalog.dirty, previousVersionId: all.sort((a, b) => a.createdAt.localeCompare(b.createdAt)).at(-1)?.versionId ?? null, scannerVersions: { catalog: "0.1.5", symbols: "0.1.6" }, warnings: [] };
  await validateWithSchema(lab, "framework-version.schema.json", version); const output = vroot(lab, frameworkId, "versions", versionId); await writeJson(path.join(output, "version.json"), version); await writeJson(path.join(output, "manifest.json"), { schemaVersion: "1.0.0", versionId, versionSha256: sha(await readFile(path.join(output, "version.json"))) }); await writeJson(vroot(lab, frameworkId, "current.json"), { schemaVersion: "1.0.0", versionId, sourceCommit, updatedAt: now() }); return version;
}
export async function validateVersion(lab: string, frameworkId: string, versionId: string) { const version = await json<FrameworkVersion>(vroot(lab, frameworkId, "versions", versionId, "version.json")); await validateWithSchema(lab, "framework-version.schema.json", version); const data = await snapshot(lab, frameworkId, version.catalogSnapshotId, version.symbolSnapshotId); if (data.catalog.sourceCommit !== version.sourceCommit || data.catalog.rootHash !== version.catalogRootHash || data.symbols.rootHash !== version.symbolRootHash) throw new Error("Version Snapshot 引用不一致。"); const manifest = await json<{ versionSha256: string }>(vroot(lab, frameworkId, "versions", versionId, "manifest.json")); if (manifest.versionSha256 !== sha(await readFile(vroot(lab, frameworkId, "versions", versionId, "version.json")))) throw new Error("Version Manifest SHA256 不匹配。"); return version; }
export async function listVersions(lab: string, frameworkId: string) { return (await versions(lab, frameworkId)).sort((a, b) => a.createdAt.localeCompare(b.createdAt)); }

function count(value: unknown) { return Array.isArray(value) ? value.length : 0; }
export async function createVersionDiff(lab: string, frameworkId: string, fromId: string, toId: string) {
  const [from, to] = await Promise.all([validateVersion(lab, frameworkId, fromId), validateVersion(lab, frameworkId, toId)]);
  const catalog = await diffCatalog(lab, frameworkId, from.catalogSnapshotId, to.catalogSnapshotId, true); const symbols = await diffSymbols(lab, frameworkId, from.symbolSnapshotId, to.symbolSnapshotId, true);
  const diffId = `${fromId}--${toId}`; const catalogChanges = catalog as Record<string, unknown>, symbolChanges = symbols as Record<string, unknown>;
  const sourceFiles = { added: catalogChanges.added ?? [], removed: catalogChanges.removed ?? [], modified: catalogChanges.modified ?? [], moved: catalogChanges.renamed ?? [], reclassified: catalogChanges.reclassified ?? [] }; const severitySummary = { files: count(sourceFiles.added) + count(sourceFiles.removed) + count(sourceFiles.modified), symbols: count((symbolChanges.symbols as Record<string, unknown>)?.added) + count((symbolChanges.symbols as Record<string, unknown>)?.removed) + count((symbolChanges.symbols as Record<string, unknown>)?.modified), publicApi: count((symbolChanges.exports as Record<string, unknown>)?.added) + count((symbolChanges.exports as Record<string, unknown>)?.removed) };
  const business = { from: sha(JSON.stringify(from)), to: sha(JSON.stringify(to)), catalog, symbols, rules: "1.0.0" };
  const result = { schemaVersion: "1.0.0", diffId, frameworkId, fromVersionId: fromId, toVersionId: toId, fromCommit: from.sourceCommit, toCommit: to.sourceCommit, catalogDiffId: `${from.catalogSnapshotId}--${to.catalogSnapshotId}`, symbolDiffId: `${from.symbolSnapshotId}--${to.symbolSnapshotId}`, sourceFiles, packages: { added: catalogChanges.packageAdded ?? [], removed: catalogChanges.packageRemoved ?? [], modified: catalogChanges.packageModified ?? [] }, documents: catalogChanges.documentsChanged ?? {}, examples: catalogChanges.examplesChanged ?? {}, configs: catalogChanges.configsChanged ?? {}, modules: symbolChanges.modules ?? {}, symbols: symbolChanges.symbols ?? {}, exports: symbolChanges.exports ?? {}, publicApi: symbolChanges.exports ?? {}, components: symbolChanges.components ?? {}, relationships: symbolChanges.relationships ?? {}, diagnostics: {}, severitySummary, generatedAt: now(), rootHash: sha(JSON.stringify(business)), warnings: ["Structural changes are not automatically classified as breaking changes."] };
  await validateWithSchema(lab, "framework-version-diff.schema.json", result); const output = vroot(lab, frameworkId, "diffs", diffId); await mkdir(output, { recursive: true }); await Promise.all([writeJson(path.join(output, "version-diff.json"), result), writeJson(path.join(output, "catalog-diff.json"), catalog), writeJson(path.join(output, "symbol-diff.json"), symbols)]); await writeFile(path.join(output, "report.md"), `# Version Diff ${diffId}\n\n- From: ${from.sourceCommit}\n- To: ${to.sourceCommit}\n- File changes: ${severitySummary.files}\n- Symbol changes: ${severitySummary.symbols}\n- Public export changes: ${severitySummary.publicApi}\n\nStructural change is not automatically a breaking-change conclusion.\n`, "utf8"); await writeJson(path.join(output, "manifest.json"), { schemaVersion: "1.0.0", diffId, rootHash: result.rootHash, files: Object.fromEntries(await Promise.all(["version-diff.json", "catalog-diff.json", "symbol-diff.json", "report.md"].map(async (file) => [file, sha(await readFile(path.join(output, file)))]))) }); return result;
}

async function bundleEvidence(lab: string, frameworkId: string, bundleId: string) { return json<{ evidence: Array<{ id: string; sourcePath: string; sha256: string }> }>(lroot(lab, frameworkId, "bundles", bundleId, "evidence.json")); }
export async function knowledgeImpact(lab: string, frameworkId: string, diffId: string) {
  const vd = await json<{ fromVersionId: string; toVersionId: string; fromCommit: string; toCommit: string }>(vroot(lab, frameworkId, "diffs", diffId, "version-diff.json")); const [from, to, units] = await Promise.all([validateVersion(lab, frameworkId, vd.fromVersionId), validateVersion(lab, frameworkId, vd.toVersionId), listPublished(lab, frameworkId)]);
  const [oldFiles, newFiles] = await Promise.all([json<{ files: Array<{ path: string; sha256: string }> }>(path.join(lab, "frameworks", frameworkId, "catalog", "snapshots", from.catalogSnapshotId, "files.json")), json<{ files: Array<{ path: string; sha256: string }> }>(path.join(lab, "frameworks", frameworkId, "catalog", "snapshots", to.catalogSnapshotId, "files.json"))]); const oldByPath = new Map(oldFiles.files.map((item) => [item.path, item.sha256])), newByPath = new Map(newFiles.files.map((item) => [item.path, item.sha256]));
  const evidence: Array<Record<string, unknown>> = [], claims: Array<Record<string, unknown>> = [], unitRows: Array<Record<string, unknown>> = [];
  for (const unit of units) {
    const refs = await bundleEvidence(lab, frameworkId, unit.sourceBundleId).catch(() => ({ evidence: [] })); const statuses = refs.evidence.map((ref) => { const oldHash = oldByPath.get(ref.sourcePath), newHash = newByPath.get(ref.sourcePath); const relocated = oldHash ? oldFiles.files.filter((item) => item.sha256 === oldHash).length === 1 && newFiles.files.filter((item) => item.sha256 === oldHash).length === 1 && !newHash : false; const status = newHash === ref.sha256 && oldHash === ref.sha256 ? "unchanged" : newHash === ref.sha256 && relocated ? "relocated" : !newHash ? "removed" : oldHash === undefined ? "newly_available" : "changed"; const row = { evidenceId: ref.id, knowledgeId: unit.id, sourcePath: ref.sourcePath, status, oldSha256: oldHash ?? null, newSha256: newHash ?? null }; evidence.push(row); return row; });
    const targetMatches = unit.scope.sourceCommit === to.sourceCommit; for (const claim of unit.claims) { const affected = statuses.filter((item) => claim.evidenceIds.includes(String(item.evidenceId)) && !["unchanged", "relocated"].includes(String(item.status))); const freshnessStatus = targetMatches ? "current" : affected.length ? "stale" : claim.status === "manual" ? "partially_stale" : "carried_forward"; claims.push({ claimId: claim.id, knowledgeId: unit.id, previousStatus: claim.status, freshnessStatus, impactLevel: affected.length ? "medium" : "none", evidenceStatuses: statuses.map((item) => item.status), affectedEvidence: affected.map((item) => item.evidenceId), unchangedEvidence: statuses.filter((item) => ["unchanged", "relocated"].includes(String(item.status))).map((item) => item.evidenceId), reasons: targetMatches ? ["knowledge scope already matches target commit"] : affected.length ? ["referenced evidence changed"] : ["all referenced evidence stable"], autoCarryForwardEligible: !targetMatches && !affected.length && claim.status === "observed", revalidationRequired: claim.status === "verified" && !targetMatches, manualReviewRequired: claim.status === "manual", recommendedAction: targetMatches ? "keep" : affected.length ? "relearn" : "carry_forward", targetScope: to.sourceCommit, warnings: [] }); }
    const claimRows = claims.filter((item) => item.knowledgeId === unit.id); const freshnessStatus = targetMatches ? "current" : claimRows.some((item) => item.freshnessStatus === "stale") ? "stale" : "partially_stale"; unitRows.push({ knowledgeId: unit.id, publicationStatus: unit.publicationStatus, freshnessStatus, affectedClaimCount: claimRows.filter((item) => item.freshnessStatus !== "current" && item.freshnessStatus !== "carried_forward").length, requiredClaimAffectedCount: 0, recommendedAction: targetMatches ? "keep" : freshnessStatus === "stale" ? "relearn" : "carry_forward", impactId: `impact-${diffId}` }); }
  const impactId = `impact-${diffId}`, business = { from: from.versionId, to: to.versionId, evidence: evidence.slice().sort((a, b) => JSON.stringify(a).localeCompare(JSON.stringify(b))), claims: claims.slice().sort((a, b) => JSON.stringify(a).localeCompare(JSON.stringify(b))), rules: "1.0.0" }; const impact = { schemaVersion: "1.0.0", impactId, frameworkId, versionDiffId: diffId, fromVersionId: from.versionId, toVersionId: to.versionId, generatedAt: now(), rootHash: sha(JSON.stringify(business)), propagationRulesVersion: "1.0.0", summary: { units: unitRows.length, affected: unitRows.filter((item) => item.freshnessStatus !== "current").length, evidenceChanged: evidence.filter((item) => item.status === "changed").length }, warnings: [] }; await Promise.all([validateWithSchema(lab, "evidence-impact.schema.json", { evidence }), validateWithSchema(lab, "claim-impact.schema.json", { claims }), validateWithSchema(lab, "knowledge-impact.schema.json", impact)]); const output = lroot(lab, frameworkId, "impacts", impactId); await mkdir(output, { recursive: true }); await Promise.all([writeJson(path.join(output, "impact.json"), impact), writeJson(path.join(output, "claims.json"), { claims }), writeJson(path.join(output, "units.json"), { units: unitRows }), writeJson(path.join(output, "topics.json"), { topics: [] })]); await writeFile(path.join(output, "report.md"), `# Knowledge Impact ${impactId}\n\n- Units: ${impact.summary.units}\n- Affected: ${impact.summary.affected}\n- Evidence changed: ${impact.summary.evidenceChanged}\n`, "utf8"); await writeJson(path.join(output, "manifest.json"), { schemaVersion: "1.0.0", impactId, rootHash: impact.rootHash, files: Object.fromEntries(await Promise.all(["impact.json", "claims.json", "units.json", "topics.json", "report.md"].map(async (file) => [file, sha(await readFile(path.join(output, file)))]))) }); return impact;
}
export async function freshness(lab: string, frameworkId: string, targetVersion?: string) { const all = await listVersions(lab, frameworkId); const target = targetVersion ? all.find((item) => item.versionId === targetVersion) : all.at(-1); if (!target) throw new Error("没有可用 Framework Version。"); const impacts = await readdir(lroot(lab, frameworkId, "impacts")).catch(() => []); const latest = impacts.sort().at(-1); const rows = latest ? (await json<{ units: Array<Record<string, unknown>> }>(lroot(lab, frameworkId, "impacts", latest, "units.json"))).units : (await listPublished(lab, frameworkId)).map((unit) => ({ knowledgeId: unit.id, publicationStatus: unit.publicationStatus, freshnessStatus: unit.scope.sourceCommit === target.sourceCommit ? "current" : "unresolved", impactId: null })); return { targetVersionId: target.versionId, targetCommit: target.sourceCommit, rows }; }
